call pathogen#infect()
" Enable filetype-specific indenting
" Enable filetype-specific plugins
filetype plugin indent on
set nocompatible      " We're running Vim, not Vi!
syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
autocmd FileType ruby compiler ruby
