"FOr getting vim to compile on LION see - https://gist.github.com/1109948
call pathogen#infect()
" Enable filetype-specific indenting
" Enable filetype-specific plugins
filetype plugin indent on
set nocompatible      " We're running Vim, not Vi!
syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
autocmd FileType ruby compiler ruby
"autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
"ruby
"I dont think any of these are working
"autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
"autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
"autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
"autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
""improve autocomplete menu color
highlight Pmenu ctermbg=238 gui=bold
"uncomment below to enable nerdtree by default
"autocmd vimenter * NERDTree
" using control+T to toggle directory list
nmap <silent> <C-T> :NERDTreeToggle<CR>
set paste

"for opening classes on current line in navigate mode by g and then f
"set path+=/path/to/your/rails-application/app/**
"set path+=/path/to/your/rails-application/lib/**
"set suffixesadd=.rb
"set includeexpr+=substitute(v:fname,'s$','','g')
" or you can add substitution pattern s/ies$/y/g, s/ves$/f/g like this:
" set includeexpr+=substitute(substitute(substitute(v:fname,'s$','','g'),'ie$','y','g'),'ve$','f','g')

"use - http://www.vim.org/scripts/script.php?script_id=273
":TlistToggle
nmap <silent> <C-L> :TlistToggle<CR>
autocmd BufEnter *
	    \ if exists("b:rails_root") |
	    \   let g:base_dir = b:rails_root |
	    \ endif |
